/* ============================================================
   B2 Read — 關聯學習系統：詞庫（tools/build-rel.js 使用）

   這裡只放「知識」：哪些字是近義／易混淆、哪些是反義、哪些是不規則詞族。
   build-rel.js 會拿這份清單去對「使用者實際學過的字」（data-book.js 的
   vocab / vocab2 / phrases / colloc / extraVocab），**只有雙方都學過**才建立關聯；
   沒學過的字絕對不會因為出現在這裡而被塞進網站。

   內容原則（使用者 2026-09-08 指定：學習者無法自行判斷對錯，寧缺勿濫）：
   - 只寫有把握的、教科書等級的區別，說明用繁體中文、台灣用語。
   - 差異說明要「一句講完」，重點是「什麼時候用哪個」。
   - pat 只寫最典型的搭配骨架（sb / sth / to V / that…）。
   ============================================================ */

/* 近義／易混淆：members 兩個以上；d = 各字的一句差異；tip = 快速記憶（可省略） */
const SYN = [
  { m:['persuade','convince'], concept:'說服',
    d:{ persuade:'偏向說服某人去「做」某事 → persuade sb to V', convince:'偏向使某人「相信」某件事 → convince sb that…' },
    pat:{ persuade:'persuade sb to V', convince:'convince sb that…' },
    tip:'persuade 推人去行動；convince 讓人點頭相信。' },
  { m:['concentrate','focus'], concept:'專心',
    d:{ concentrate:'需要出力、排除干擾地專注 → concentrate on', focus:'把注意力放在某個重點上，最常用、較中性 → focus on' } },
  { m:['effective','efficient'], concept:'有效 vs 有效率',
    d:{ effective:'有效的：做到了想要的效果（結果）', efficient:'有效率的：不浪費時間或資源（過程）' },
    tip:'effective 看結果，efficient 看過程。' },
  { m:['effectively','efficiently'], concept:'有效地 vs 有效率地',
    d:{ effectively:'有效地：達到目的', efficiently:'有效率地：省時省力' } },
  { m:['borrow','lend'], concept:'借',
    d:{ borrow:'借入（我向別人借）→ borrow sth from sb', lend:'借出（我借給別人）→ lend sb sth / lend sth to sb' },
    pat:{ borrow:'borrow sth from sb', lend:'lend sth to sb' } },
  { m:['say','tell'], concept:'說',
    d:{ say:'說（後面直接接話的內容）→ say (that)…', tell:'告訴某人 → tell sb (that)… ／ tell sb to V' },
    pat:{ say:'say (that)…', tell:'tell sb that… / tell sb to V' } },
  { m:['speak','talk'], concept:'講話',
    d:{ speak:'較正式；講某種語言、對群眾發言 → speak English / speak to sb', talk:'較口語；聊天、交談 → talk to / with sb about sth' } },
  { m:['hear','listen'], concept:'聽',
    d:{ hear:'聽到（不刻意，聲音自己進來）', listen:'注意聽（刻意的動作）→ listen to' },
    pat:{ listen:'listen to sth/sb' } },
  { m:['see','watch','look'], concept:'看',
    d:{ see:'看到（不刻意）', watch:'盯著會動的東西看一段時間（電視、比賽）', look:'看一眼、把視線轉過去 → look at' },
    pat:{ look:'look at sth' } },
  { m:['remember','remind'], concept:'記得 vs 提醒',
    d:{ remember:'自己記得 → remember to V（記得要做）／ remember V-ing（記得做過）', remind:'提醒別人 → remind sb to V / remind sb of sth' },
    pat:{ remind:'remind sb to V' } },
  { m:['bring','take'], concept:'帶',
    d:{ bring:'帶「來」說話者所在的地方', take:'帶「去」別的地方' } },
  { m:['come','go'], concept:'來 vs 去',
    d:{ come:'朝說話者或聽者的方向移動', go:'離開，往別處移動' } },
  { m:['trip','travel','journey'], concept:'旅行',
    d:{ trip:'一趟（可數）短程旅行 → a trip to…', travel:'旅行這件事（多當動詞或不可數名詞）', journey:'一段路程本身，強調移動過程' } },
  { m:['job','work'], concept:'工作',
    d:{ job:'一份工作（可數）→ a job', work:'工作這件事（不可數）→ work（不加 a）' } },
  { m:['fun','funny'], concept:'有趣',
    d:{ fun:'好玩的、令人開心的（名詞/形容詞）', funny:'好笑的、滑稽的' } },
  { m:['lose','miss'], concept:'錯過／弄丟',
    d:{ lose:'弄丟、失去 → lose my keys / lose weight', miss:'錯過（車、機會）、想念 → miss the bus / miss you' } },
  { m:['wait','expect','look forward to'], concept:'等待／期待',
    d:{ wait:'等（時間上的等待）→ wait for', expect:'預期會發生 → expect sth / expect to V', 'look forward to':'期待（開心地等）→ look forward to V-ing' },
    pat:{ wait:'wait for sb/sth', expect:'expect to V', 'look forward to':'look forward to V-ing' } },
  { m:['raise','rise'], concept:'上升',
    d:{ raise:'及物：把某物提高 → raise prices / raise my hand', rise:'不及物：自己上升 → prices rise' } },
  { m:['affect','effect'], concept:'影響',
    d:{ affect:'動詞：影響 → affect sth', effect:'名詞：影響、效果 → have an effect on' },
    pat:{ effect:'have an effect on sth' } },
  { m:['advice','advise'], concept:'建議',
    d:{ advice:'名詞（不可數）→ a piece of advice', advise:'動詞 → advise sb to V' },
    pat:{ advise:'advise sb to V' } },
  { m:['practice','practise'], concept:'練習',
    d:{ practice:'名詞（美式也當動詞）', practise:'英式動詞' } },
  { m:['illness','sickness','disease'], concept:'生病',
    d:{ illness:'生病的狀態（通用）', sickness:'不舒服、想吐的感覺', disease:'醫學上明確的疾病名' } },
  { m:['stuck','blocked'], concept:'卡住',
    d:{ stuck:'（人或物）動彈不得的狀態 → be stuck in traffic', blocked:'（通道、管線）被堵住 → the road is blocked' } },
  { m:['satisfied','satisfactory'], concept:'滿意',
    d:{ satisfied:'人感到滿意 → be satisfied with', satisfactory:'東西令人滿意、及格的' },
    pat:{ satisfied:'be satisfied with sth' } },
  { m:['join','attend'], concept:'參加',
    d:{ join:'加入（團體、活動）成為一員 → join a club', attend:'出席（會議、課程）→ attend a meeting' } },
  { m:['comfortable','comforting'], concept:'舒服／安慰',
    d:{ comfortable:'（人或物）舒服的', comforting:'令人感到安慰的' } },
  { m:['aim','goal','target'], concept:'目標',
    d:{ aim:'想達成的方向（較抽象）', goal:'具體想達成的目標', target:'量化的目標數字或對象' } },
  { m:['chemistry','rapport'], concept:'默契',
    d:{ chemistry:'兩人之間自然的來電、合拍', rapport:'透過相處建立的信任與好關係 → build rapport with sb' },
    pat:{ rapport:'build / have a good rapport with sb' } },
  { m:['relieve','release'], concept:'解除／釋放',
    d:{ relieve:'減輕（痛苦、壓力）→ relieve stress', release:'釋放、發布 → release a product' },
    pat:{ relieve:'relieve stress / pain' } },
  { m:['problem','trouble','issue'], concept:'問題',
    d:{ problem:'需要解決的問題（可數）', trouble:'麻煩、困境（多不可數）→ be in trouble', issue:'議題、待討論的問題（較正式）' } },
  { m:['big','large','huge'], concept:'大',
    d:{ big:'最口語、通用', large:'較正式；尺寸、數量大', huge:'非常大' } },
  { m:['small','little','tiny'], concept:'小',
    d:{ small:'尺寸小（客觀）', little:'小而帶感情（可愛、少量）', tiny:'非常小' } },
  { m:['begin','start'], concept:'開始',
    d:{ begin:'較正式', start:'較口語；也可指發動機器、創業' } },
  { m:['finish','complete','end'], concept:'完成／結束',
    d:{ finish:'做完某事 → finish V-ing', complete:'完成（較正式，強調全部做完）', end:'結束、終止（狀態）' },
    pat:{ finish:'finish V-ing' } },
  { m:['error','mistake'], concept:'錯誤',
    d:{ error:'較正式；技術或計算上的錯誤', mistake:'一般的錯誤 → make a mistake' },
    pat:{ mistake:'make a mistake' } },
  { m:['customer','client'], concept:'客戶',
    d:{ customer:'買東西的顧客', client:'接受專業服務的客戶（律師、顧問）' } },
  { m:['salary','wage','pay'], concept:'薪水',
    d:{ salary:'月薪／年薪', wage:'時薪／日薪', pay:'薪酬（通稱）' } },
  { m:['damage','harm','hurt'], concept:'傷害',
    d:{ damage:'對物品的損壞（不可數）', harm:'對人或事物的傷害（較抽象）', hurt:'弄痛、傷到（人的身體或感情）' } },
  { m:['delay','postpone','cancel'], concept:'延後／取消',
    d:{ delay:'延誤、耽擱（常被動）→ be delayed', postpone:'主動改期 → postpone sth to/until', cancel:'取消' } },
  { m:['worried','anxious','nervous'], concept:'擔心／緊張',
    d:{ worried:'擔心（有具體的事）→ be worried about', anxious:'焦慮（較強烈、持續）', nervous:'緊張（面對即將發生的事）' },
    pat:{ worried:'be worried about sth' } },
  { m:['stressed','overwhelmed'], concept:'壓力大',
    d:{ stressed:'感到有壓力 → feel stressed', overwhelmed:'壓力大到難以應付、招架不住 → feel overwhelmed' } },
  { m:['angry','mad','upset'], concept:'生氣',
    d:{ angry:'生氣（通用）→ be angry with sb / at sth', mad:'口語的生氣（美式）', upset:'難過又不高興（偏傷心）' } },
  { m:['tired','exhausted'], concept:'累',
    d:{ tired:'累', exhausted:'累到不行、筋疲力盡' } },
  { m:['cheap','affordable','inexpensive'], concept:'便宜',
    d:{ cheap:'便宜（可能帶「品質差」的意味）', affordable:'負擔得起的（正面）', inexpensive:'不貴的（中性、較禮貌）' } },
  { m:['house','home'], concept:'家',
    d:{ house:'房子（建築物）', home:'家（住的地方、歸屬感）→ go home（不加 to）' } },
  { m:['clothes','clothing','cloth'], concept:'衣服',
    d:{ clothes:'衣服（複數，日常用）', clothing:'服裝（總稱，較正式）', cloth:'布料' } },
  { m:['interesting','interested'], concept:'有趣 vs 感興趣',
    d:{ interesting:'（事物）有趣的', interested:'（人）感興趣的 → be interested in' },
    pat:{ interested:'be interested in sth' } },
  { m:['boring','bored'], concept:'無聊',
    d:{ boring:'（事物）令人無聊的', bored:'（人）感到無聊的 → be bored with' } },
  { m:['exciting','excited'], concept:'興奮',
    d:{ exciting:'（事物）令人興奮的', excited:'（人）感到興奮的 → be excited about' } },
  { m:['frustrating','frustrated'], concept:'挫折',
    d:{ frustrating:'（事物）令人沮喪的', frustrated:'（人）感到挫折的 → be frustrated with' } },
  { m:['relaxing','relaxed'], concept:'放鬆',
    d:{ relaxing:'（事物）令人放鬆的', relaxed:'（人）放鬆的' } },
  { m:['confusing','confused'], concept:'困惑',
    d:{ confusing:'（事物）令人困惑的', confused:'（人）感到困惑的' } },
  { m:['surprising','surprised'], concept:'驚訝',
    d:{ surprising:'（事物）令人驚訝的', surprised:'（人）感到驚訝的 → be surprised at/by' } },
  { m:['embarrassing','embarrassed'], concept:'尷尬',
    d:{ embarrassing:'（事物）令人尷尬的', embarrassed:'（人）感到尷尬的' } },
  { m:['get past','move over'], concept:'讓路',
    d:{ 'get past':'我要從你旁邊過去（我動，對方不動）', 'move over':'請你挪過去一點（我不動，對方動）' } },
  { m:['leave','forget'], concept:'忘了帶 vs 忘記',
    d:{ leave:'把東西留在某處（重點是「在哪裡」）→ leave sth at/in…', forget:'忘記做或忘記某事（重點是「記憶」）→ forget to V' },
    pat:{ forget:'forget to V' } },
  { m:['arrive','reach','get to'], concept:'抵達',
    d:{ arrive:'arrive at + 小地點 / arrive in + 大地點 / arrive home', reach:'及物，直接接地點 → reach the station', 'get to':'口語 → get to work / get home' },
    pat:{ arrive:'arrive at / in + 地點' } },
  { m:['refund','return','exchange'], concept:'退款／退貨／換貨',
    d:{ refund:'退錢 → get a refund', return:'退貨（把東西還回去）', exchange:'換貨 → exchange sth for sth' },
    pat:{ refund:'get / ask for a refund' } },
  { m:['apologize','sorry'], concept:'道歉',
    d:{ apologize:'動詞：道歉 → apologize to sb for sth', sorry:'形容詞 → be sorry for / about' },
    pat:{ apologize:'apologize to sb for sth' } },
  { m:['discuss','argue','debate'], concept:'討論／爭論',
    d:{ discuss:'討論（及物，不加 about）→ discuss sth', argue:'爭吵、爭辯 → argue with sb about sth', debate:'正式辯論' },
    pat:{ discuss:'discuss sth（不加 about）' } },
  { m:['explain','describe'], concept:'解釋／描述',
    d:{ explain:'說明原因或做法 → explain sth to sb', describe:'描述樣子或過程' },
    pat:{ explain:'explain sth to sb' } },
  { m:['suggest','recommend'], concept:'建議',
    d:{ suggest:'提出想法 → suggest V-ing / suggest that…', recommend:'推薦（覺得好才推）→ recommend sth / recommend V-ing' },
    pat:{ suggest:'suggest V-ing / suggest that…' } },
  { m:['accept','receive'], concept:'接受／收到',
    d:{ accept:'接受（同意收下）', receive:'收到（客觀地拿到）' } },
  { m:['avoid','prevent'], concept:'避免／防止',
    d:{ avoid:'避開 → avoid V-ing', prevent:'防止（使不發生）→ prevent sb from V-ing' },
    pat:{ avoid:'avoid V-ing', prevent:'prevent sb from V-ing' } },
  { m:['check','confirm'], concept:'查核／確認',
    d:{ check:'檢查、查看', confirm:'確認（正式證實）' } },
  { m:['fix','repair','mend'], concept:'修理',
    d:{ fix:'口語：修好、解決', repair:'修理（較正式，大型物件）', mend:'修補（衣物、小東西）' } },
  { m:['worth','worthy'], concept:'值得',
    d:{ worth:'be worth + V-ing / 名詞（值得做）', worthy:'be worthy of（配得上、有價值）' },
    pat:{ worth:'be worth V-ing' } },
  { m:['used to','be used to','get used to'], concept:'過去習慣 vs 習慣於',
    d:{ 'used to':'過去常常（現在不再）→ used to + V', 'be used to':'已經習慣 → be used to + V-ing / 名詞', 'get used to':'逐漸習慣 → get used to + V-ing' },
    pat:{ 'used to':'used to V', 'be used to':'be used to V-ing', 'get used to':'get used to V-ing' } },
  { m:['stop to','stop'], concept:'停下來做 vs 停止做',
    d:{ 'stop to':'停下來去做另一件事 → stop to V', stop:'停止正在做的事 → stop V-ing' } },
  { m:['spoiled','rotten'], concept:'壞掉的食物',
    d:{ spoiled:'（食物）壞掉、變質', rotten:'腐爛（更嚴重，會有味道）' } },
  { m:['damp','wet','humid'], concept:'潮濕',
    d:{ damp:'微濕、潮潮的（不舒服）', wet:'濕的（有水）', humid:'（天氣）濕度高' } },
  { m:['scare','scared','scary'], concept:'害怕',
    d:{ scare:'動詞：嚇 → scare sb', scared:'（人）害怕的 → be scared of', scary:'（事物）可怕的' } },
  { m:['nausea','nauseous'], concept:'噁心',
    d:{ nausea:'名詞：噁心感', nauseous:'形容詞：想吐的 → feel nauseous' } },
  { m:['optimistic','pessimistic'], concept:'樂觀／悲觀', ant:true,
    d:{ optimistic:'樂觀的 → be optimistic about', pessimistic:'悲觀的' } },
];

/* 反義：兩兩一組（會自動配對 both-learned），d 可省略 */
const ANT = [
  ['deny','admit'], ['agree','disagree'], ['accept','refuse'], ['accept','reject'], ['increase','decrease'],
  ['arrive','depart'], ['arrive','leave'], ['remember','forget'], ['succeed','fail'], ['success','failure'],
  ['borrow','lend'], ['buy','sell'], ['win','lose'], ['gain','lose'], ['hire','fire'], ['employ','dismiss'],
  ['strength','weakness'], ['strong','weak'], ['positive','negative'], ['optimistic','pessimistic'],
  ['optimist','pessimist'], ['polite','rude'], ['patient','impatient'], ['possible','impossible'],
  ['formal','informal'], ['regular','irregular'], ['legal','illegal'], ['honest','dishonest'],
  ['reliable','unreliable'], ['comfortable','uncomfortable'], ['expensive','cheap'], ['expensive','affordable'],
  ['early','late'], ['on time','late'], ['full-time','part-time'], ['indoor','outdoor'], ['indoors','outdoors'],
  ['upstairs','downstairs'], ['tight','loose'], ['wide','narrow'], ['deep','shallow'], ['heavy','light'],
  ['fresh','stale'], ['fresh','rotten'], ['raw','cooked'], ['sweet','sour'], ['dry','damp'], ['dry','wet'],
  ['calm','nervous'], ['relaxed','stressed'], ['confident','nervous'], ['tidy','messy'], ['clean','dirty'],
  ['safe','dangerous'], ['safety','danger'], ['advantage','disadvantage'], ['pro','con'],
  ['include','exclude'], ['import','export'], ['landlord','tenant'], ['employer','employee'],
  ['permanent','temporary'], ['ancient','modern'], ['rural','urban'], ['major','minor'],
  ['maximum','minimum'], ['cause','effect'], ['question','answer'], ['problem','solution'],
  ['be down','be back up'], ['turn on','turn off'], ['pick up','drop off'], ['check in','check out'],
  ['take off','land'], ['departure','arrival'], ['sunrise','sunset'], ['praise','criticize'],
  ['encourage','discourage'], ['generous','stingy'], ['humble','arrogant'], ['flexible','rigid'],
  ['approve','reject'], ['attach','detach'], ['connect','disconnect'], ['appear','disappear'],
];

/* 詞族補充：規則式 stemmer 抓不到的不規則變化（同一族放同一個陣列）。
   規則能抓到的（effective/effectively、encourage/encouraging/encouragement…）不用寫。 */
const FAM = [
  ['succeed','success','successful','successfully'], ['decide','decision'], ['choose','choice'],
  ['explain','explanation'], ['describe','description'], ['advise','advice'], ['believe','belief'],
  ['prove','proof'], ['live','life','alive'], ['strong','strength','strengthen'], ['long','length','lengthen'],
  ['wide','width','widen'], ['deep','depth','deepen'], ['high','height'], ['sell','sale'], ['speak','speech'],
  ['think','thought'], ['know','knowledge'], ['grow','growth'], ['die','death','dead'], ['hot','heat'],
  ['warm','warmth'], ['true','truth'], ['weigh','weight'], ['fly','flight'], ['see','sight'],
  ['lose','loss','lost'], ['free','freedom'], ['wise','wisdom'], ['safe','safety','safely','unsafe'],
  ['able','ability','enable','unable'], ['comfort','comfortable','comforting','uncomfortable'],
  ['relieve','relief','relieved'], ['stress','stressed','stressful'], ['pressure','press'],
  ['efficient','efficiency','efficiently'], ['effective','effectively','effectiveness'],
  ['concern','concerned','concerning'], ['confide','confident','confidence'], ['patient','patience','impatient'],
  ['pronounce','pronunciation'], ['maintain','maintenance'], ['complain','complaint'], ['apologize','apology'],
  ['persuade','persuasive','persuasion'], ['convince','convincing','convinced'], ['deny','denial'],
  ['admit','admission'], ['satisfy','satisfied','satisfying','satisfactory','satisfaction'],
  ['produce','product','production','productive'], ['compete','competition','competitive','competitor'],
  ['inspect','inspection','inspector'], ['deliver','delivery'], ['receive','receipt','reception'],
  ['refund','refundable'], ['repair','repairable'], ['rely','reliable','reliability','unreliable'],
  ['depend','dependent','dependable','independent'], ['respond','response','responsible','responsibility'],
  ['organize','organization','organized'], ['prepare','preparation','prepared'], ['expect','expectation','unexpected'],
  ['assist','assistant','assistance'], ['manage','manager','management'], ['employ','employee','employer','employment','unemployed'],
  ['interview','interviewer','interviewee'], ['train','trainer','trainee','training'],
  ['flood','flooded','flooding'], ['injure','injured','injury'], ['damage','damaged'], ['destroy','destruction'],
  ['imagine','imagination','imaginative'], ['create','creative','creativity','creation'], ['solve','solution'],
  ['collect','collection'], ['protect','protection','protective'], ['prevent','prevention'],
  ['argue','argument'], ['discuss','discussion'], ['suggest','suggestion'], ['recommend','recommendation'],
  ['propose','proposal'], ['perform','performance','performer'], ['act','action','active','activity','actor'],
  ['grateful','gratitude'], ['anxious','anxiety'], ['nervous','nervousness'], ['angry','anger'],
  ['envy','envious'], ['jealous','jealousy'], ['generous','generosity'], ['humble','humility'],
  ['honest','honesty','dishonest'], ['polite','politeness','impolite'], ['curious','curiosity'],
  ['optimist','optimistic','optimism'], ['pessimist','pessimistic','pessimism'],
  ['nausea','nauseous'], ['vomit','vomiting'], ['dizzy','dizziness'], ['spoil','spoiled'], ['rot','rotten'],
  ['taste','tasty','tasteless'], ['humid','humidity'], ['damp','dampness'],
];

/* 情境鏈：由輕到重／由前到後的一串說法（成員全部學過才成立）。steps 是每一步的常見搭配（可省略）。 */
const CHAIN = [
  { m:['pressure','stressed','overwhelmed'], concept:'壓力由小到大',
    steps:['work under pressure','feel stressed','feel overwhelmed'],
    cn:'承受壓力 → 感到緊張 → 招架不住（難以應付）' },
  { m:['tired','exhausted'], concept:'累的程度', steps:['feel tired','be exhausted'], cn:'累 → 累到不行' },
  { m:['worried','anxious'], concept:'擔心的程度', steps:['be worried about','feel anxious'], cn:'擔心 → 焦慮' },
  { m:['delay','cancel'], concept:'航班狀況', steps:['be delayed','be cancelled'], cn:'延誤 → 取消' },
];

module.exports = { SYN, ANT, FAM, CHAIN };
